"""
PDF export functionality using WeasyPrint.

Converts markdown documents to well-formatted PDFs with styling.
"""
from pathlib import Path
from typing import Optional, Dict
from datetime import datetime

import markdown2
from weasyprint import HTML, CSS
from pygments.formatters import HtmlFormatter


class PDFExporter:
    """Handle PDF export of markdown documents."""

    def __init__(self, export_dir: Path):
        """
        Initialize PDF exporter.

        Args:
            export_dir: Directory where exported PDFs will be saved
        """
        self.export_dir = export_dir
        self.export_dir.mkdir(parents=True, exist_ok=True)

    def markdown_to_html(
        self,
        markdown_content: str,
        title: str,
        metadata: Dict[str, str]
    ) -> str:
        """
        Convert markdown to styled HTML suitable for PDF.

        Args:
            markdown_content: Raw markdown text
            title: Document title
            metadata: Dict with project, export_date, source_path

        Returns:
            Complete HTML document string
        """
        # Convert markdown to HTML with extras
        html_content = markdown2.markdown(
            markdown_content,
            extras=[
                'fenced-code-blocks',
                'tables',
                'task_list',
                'strike',
                'footnotes',
                'header-ids',
                'code-friendly',
                'cuddled-lists',
                'break-on-newline'
            ]
        )

        # Wrap in full HTML document with styling
        html_doc = self._create_html_document(
            html_content,
            title,
            metadata
        )

        return html_doc

    def _create_html_document(
        self,
        content: str,
        title: str,
        metadata: Dict[str, str]
    ) -> str:
        """
        Create complete HTML document with styling.

        Args:
            content: HTML content (converted from markdown)
            title: Document title
            metadata: Metadata dictionary

        Returns:
            Full HTML document with styles
        """
        # Get Pygments CSS for code highlighting
        pygments_css = HtmlFormatter(style='friendly').get_style_defs('.codehilite')

        return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <style>
{self._get_pdf_styles()}

/* Pygments syntax highlighting */
{pygments_css}
    </style>
</head>
<body>
    <div class="pdf-header">
        <h1 class="pdf-title">{title}</h1>
        <div class="metadata">
            <p><strong>Project:</strong> {metadata.get('project', 'Unknown')}</p>
            <p><strong>Exported:</strong> {metadata.get('export_date', 'Unknown')}</p>
            <p><strong>Source:</strong> <code>{metadata.get('source_path', 'Unknown')}</code></p>
        </div>
    </div>
    <div class="pdf-content">
{content}
    </div>
    <div class="pdf-footer">
        <p>Generated by Project Viewer</p>
    </div>
</body>
</html>
"""

    def _get_pdf_styles(self) -> str:
        """
        Return CSS styles optimized for PDF export.

        Returns:
            CSS string with print-optimized styles
        """
        return """
@page {
    size: A4;
    margin: 2cm;
    @bottom-center {
        content: "Page " counter(page) " of " counter(pages);
        font-size: 9pt;
        color: #6b7280;
    }
}

body {
    font-family: 'DejaVu Sans', 'Liberation Sans', Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #1f2937;
}

.pdf-header {
    margin-bottom: 2rem;
    padding-bottom: 1rem;
    border-bottom: 2px solid #e5e7eb;
}

.pdf-title {
    font-size: 24pt;
    margin-bottom: 0.5rem;
    color: #1f2937;
    font-weight: 700;
}

.metadata {
    font-size: 9pt;
    color: #6b7280;
}

.metadata p {
    margin: 0.25rem 0;
}

.metadata code {
    font-size: 8pt;
    color: #4b5563;
}

.pdf-content {
    margin-top: 1rem;
}

.pdf-content h1 {
    font-size: 20pt;
    margin-top: 1.5rem;
    margin-bottom: 0.75rem;
    page-break-after: avoid;
    color: #111827;
    font-weight: 700;
}

.pdf-content h2 {
    font-size: 16pt;
    margin-top: 1.25rem;
    margin-bottom: 0.5rem;
    page-break-after: avoid;
    color: #1f2937;
    font-weight: 600;
}

.pdf-content h3 {
    font-size: 14pt;
    margin-top: 1rem;
    margin-bottom: 0.5rem;
    page-break-after: avoid;
    color: #374151;
    font-weight: 600;
}

.pdf-content h4 {
    font-size: 12pt;
    margin-top: 0.75rem;
    margin-bottom: 0.5rem;
    color: #4b5563;
    font-weight: 600;
}

.pdf-content p {
    margin: 0.5rem 0;
    text-align: justify;
}

.pdf-content ul,
.pdf-content ol {
    margin: 0.75rem 0;
    padding-left: 2rem;
}

.pdf-content li {
    margin: 0.25rem 0;
}

.pdf-content a {
    color: #2563eb;
    text-decoration: underline;
}

pre {
    background-color: #f9fafb;
    border: 1px solid #d1d5db;
    border-left: 4px solid #3b82f6;
    border-radius: 4px;
    padding: 1rem;
    overflow-x: auto;
    page-break-inside: avoid;
    margin: 1rem 0;
}

code {
    font-family: 'DejaVu Sans Mono', 'Liberation Mono', 'Courier New', monospace;
    font-size: 9pt;
    background-color: #f3f4f6;
    padding: 0.2rem 0.4rem;
    border-radius: 2px;
    color: #dc2626;
}

pre code {
    background-color: transparent;
    padding: 0;
    color: inherit;
    border-radius: 0;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin: 1rem 0;
    page-break-inside: avoid;
    font-size: 10pt;
}

th, td {
    border: 1px solid #d1d5db;
    padding: 0.5rem;
    text-align: left;
}

th {
    background-color: #f3f4f6;
    font-weight: 600;
    color: #1f2937;
}

tr:nth-child(even) {
    background-color: #f9fafb;
}

img {
    max-width: 100%;
    height: auto;
    page-break-inside: avoid;
    margin: 1rem 0;
}

blockquote {
    border-left: 4px solid #d1d5db;
    padding-left: 1rem;
    margin: 1rem 0;
    color: #6b7280;
    font-style: italic;
}

hr {
    border: none;
    border-top: 2px solid #e5e7eb;
    margin: 2rem 0;
}

.pdf-footer {
    margin-top: 3rem;
    padding-top: 1rem;
    border-top: 1px solid #e5e7eb;
    font-size: 9pt;
    color: #9ca3af;
    text-align: center;
}

/* Task lists */
.pdf-content input[type="checkbox"] {
    margin-right: 0.5rem;
}

/* Footnotes */
.footnotes {
    margin-top: 2rem;
    padding-top: 1rem;
    border-top: 1px solid #e5e7eb;
    font-size: 9pt;
}

/* Prevent orphaned headings */
h1, h2, h3, h4, h5, h6 {
    page-break-after: avoid;
}

/* Keep lists together when possible */
ul, ol {
    page-break-inside: avoid;
}
"""

    def export_to_pdf(
        self,
        markdown_content: str,
        document_name: str,
        project_id: str,
        source_path: str
    ) -> Path:
        """
        Export markdown content to PDF.

        Args:
            markdown_content: Raw markdown text
            document_name: Name of the document (e.g., "README.md")
            project_id: ID of the project
            source_path: Full path to the source file

        Returns:
            Path to the generated PDF file

        Raises:
            Exception: If PDF generation fails
        """
        # Prepare metadata
        metadata = {
            'project': project_id,
            'export_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'source_path': source_path
        }

        # Convert markdown to HTML
        html_content = self.markdown_to_html(
            markdown_content,
            document_name,
            metadata
        )

        # Generate PDF filename
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        safe_name = document_name.replace('.md', '').replace(' ', '_').replace('/', '_')
        pdf_filename = f"{project_id}_{safe_name}_{timestamp}.pdf"
        pdf_path = self.export_dir / pdf_filename

        # Convert HTML to PDF
        HTML(string=html_content).write_pdf(
            pdf_path,
            presentational_hints=True
        )

        return pdf_path
